### ISSUE TITLE
Same version number, not the same code (RubyGems vs GitHub)

### ISSUE THREAD

**Issue by yadomi** [dropbox/dropbox-sdk-ruby#19]
Hi, 

The current version on [rubygems.org](https://rubygems.org/gems/dropbox-sdk) is **1.6.4**, the version on github is also **1.6.4**.

I thought everything was fine, but the **rubygems's** version is way older than **github's** one.

Will you fix the gem on rubygems, update the gem itself and bump to a new version number someday ?

**Comment by varenc** [comment]
Just updated to 1.6.5 and made sure this github and the rubygem are in sync.  Thanks for reporting this.
