### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by radex** [dropbox/dropbox-sdk-ruby#20]
I'd like to use the API added in 4d58adef, without manually touching dropbox's private parts…

It would be great if you cut a new 1.6.5 release of the ruby gem 😊

**Comment by watson** [comment]
The latest released gem is over a year old! It would be really helpful if a new version was released soon :smiley: 

/ping @cakoose

**Comment by varenc** [comment]
just did this! Apologies for the delay.
