### ISSUE TITLE
Calling metadata with a path three levels deep, e.g. "/Foo/Bar/Baz" the API responds with the first folder downcased

### ISSUE THREAD

**Issue by ablearcher9** [dropbox/dropbox-sdk-ruby#26]
For example, if I make a request like `client.metadata('/Foo/Bar')`, the API will respond correctly, with any subfolders paths being `/Foo/Bar/Baz, /Foo/Bar/Wang`, however, if I make a request like `client.metadata('/Foo/Bar/Baz')`, the API will incorrectly downcase the root folder path in any subfolder's paths, e.g. `/foo/Bar/Baz, /foo/Bar/Wang`.

Interestingly, I've only been able to recreate this using more than three levels deep. If you need any further information let me know, but it looks like this is an issue at the service API level, not the SDK, but I was unsure of how to report it so I'll start here.

**Comment by varenc** [comment]
Hey there,

Sorry for the delay. This is a known limitations with the API. We're working on improving this but its a long battle. Since this isn't an issue specifically related to the SDK I'm closing this for now.
