### ISSUE TITLE
No Response Code For put_file

### ISSUE THREAD

**Issue by dylanlive** [dropbox/dropbox-sdk-ruby#27]
I want to upload a file to dropbox and then print out its sharable link.

However, I think it would be smart to ensure the `put_file` was successful before I try to call the `shares` method on that file.

Ideally it would be nice to return a hash with a 'success' key within it, equaling true or false. I could then say `if response['success'] == true`, then...

Thoughts?

**Comment by smarx** [comment]
If the call is successful, the return value is a hash with the metadata of the uploaded file. If the call is unsuccessful, an exception will be raised.
