### ISSUE TITLE
Endpoint for permanently deleting an object

### ISSUE THREAD

**Issue by tomvo** [dropbox/dropbox-sdk-ruby#34]
It seems the `/fileops/permanently_delete` endpoint does not have a corresponding method in the SDK. Is there any reason for this?

**Comment by varenc** [comment]
hey @tomvo,

Right now this SDK is only for v1 of the Dropbox API.  Eventually we'll be updating all our SDKs to make API v2 calls and when that happens this'll be supported.  In API v2 we actually automatically generate the client methods for each API call from a structured description of our API so it'll be easy for us to always keep all our SDKs up to date.  When we finish you'll be able to see things here: https://www.dropbox.com/developers/documentation/ruby
