### ISSUE TITLE
delta(nil, path) finds no content inside directory

### ISSUE THREAD

**Issue by luopio** [dropbox/dropbox-sdk-ruby#42]
We started experiencing an issue in a service that has worked fine before where we can't find any files under a certain folder.

We're using `client.delta(nil, path)` to retrieve a deep list of all files inside a folder. Previously this worked fine, but lately we're seeing `contents: []`. Renaming the `path` folder to something else via Dropbox web UI and then copying the folder again to the original naming (or something else) fixes the issue and a new call to `delta(nil, path)` returns a proper list.

Any ideas on what is causing this? I can reproduce the issue easily on REPL:
```
require 'dropbox_sdk'
dropbox_client = DropboxClient.new(DROPBOX[:key])
path = "/DE/Berlin/2016/07/testing/2016.07.08_Duudilaastrasse_55_VH_1._OG_mitte,_10167_Berlin" 
contents = dropbox_client.delta(nil, path)
 => {"has_more"=>true, "cursor"=>"AAGNB3...", "entries"=>[["/de/berlin/2016/07/testing/2016.07.08_duudilaastrasse_55_vh_1._og_mitte,_10167_berlin", {"rev"=>"4ccf3f79eda5", "thumb_exists"=>false, "path"=>"/DE/Berlin/2016/07/testing/2016.07.08_Duudilaastrasse_55_VH_1._OG_mitte,_10167_Berlin", "is_dir"=>true, "icon"=>"folder_user", "read_only"=>false, "modifier"=>nil, "bytes"=>0, "modified"=>"Mon, 11 Jul 2016 09:32:52 +0000", "shared_folder"=>{"shared_folder_id"=>"1257444857", "is_team_only_shared_folder"=>false}, "size"=>"0 bytes", "root"=>"dropbox", "revision"=>19663}]], "reset"=>true}
```

**Comment by greg-db** [comment]
@luopio Is this only happening for a specific account? If so, it'd probably be better to close this issue and [open an API ticket](https://www.dropbox.com/developers/contact) with the user ID so we can look into it specifically for you.

In any case, is the output you shared supposed to show the issue reproduced? It seems to contain a non-empty result.

**Comment by luopio** [comment]
@greg-db I shared the folder that was causing issues with another user, created an access token and ran `delta(nil, path)` again, but the results are the same. 

Sorry about not being totally clear in the example. It does indeed list itself in `entries`, but in effect there are a few dozen folders and files inside which are not captured. What we're effectively doing is then filtering out everything except videos and images thus our microservice reports an empty directory.

It is a bit tricky to reproduce this from a clean slate as these errors are only visible after a process where
- we create a dropbox folder by copying a template folder and share it (via ruby sdk `file_copy`, sharing via a python script)
- a photographer uploads content to subfolders
- we check the folder for content via ruby sdk, which reports nothing inside the folder.

**Comment by greg-db** [comment]
@luopio I just noticed `has_more` is `true` in your sample response. Are you calling back to `delta` using the returned `cursor` in that case? 

The `delta` call normally returns more results per page than this, but in certain cases (e.g., around shared folders) you can get short pages. But in any case, apps should always call back when `has_more` is `true` in order to get the full and up to date list of entries.

If you're not already doing that, please give it a try and let me know if that doesn't fix the issue.

**Comment by luopio** [comment]
@greg-db that did it! Thanks very much. I'll just have to write up a limited loop that enquiries dropbox as long as it's telling us there is more data.

Thanks very much for your help.
