### ISSUE TITLE
No way to retrieve error codes

### ISSUE THREAD

**Issue by zwarburg** [dropbox/dropbox-sdk-ruby#48]
I have been running into issues where users are out of space on their dropbox and my app is throwing an error when we try to upload to dropbox. While the Dropbox API has a [nice set of error codes](https://www.dropbox.com/developers-v1/core/docs), I seem unable to retrieve these error codes when an error is thrown...

**Comment by greg-db** [comment]
I believe you can do something like this:

```
begin
    response = client.put_file(remote_path, local_file)
    puts "uploaded:", response.inspect
rescue DropboxError => error
    if error.http_response.kind_of? Net::HTTPInsufficientStorage
        print "Over quota"
    else
        print error
    end
end
```

Also, note that this Ruby SDK uses API v1, which is [deprecated](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/). You should migrate to [API v2](https://www.dropbox.com/developers) whenever possible.

We don't have an official Ruby SDK for API v2, but you can either use the [HTTP endpoints](https://www.dropbox.com/developers/documentation/http/documentation) directly, or use a [third party library](https://www.dropbox.com/developers/documentation/communitysdks).
