### ISSUE TITLE
corrupted download (cli example)

### ISSUE THREAD

**Issue by xiconet** [dropbox/dropbox-sdk-ruby#9]
Setting: windows xp-sp3, ruby 1.9.3
Issue: an audio/flac file downloaded with the provided `cli-example.rb` is (reproducibly) corrupted and a bit larger (approx. 1 percent) than the original. I can't tell exactly in what way the file is corrupted.
Note that the same file downloaded by other means is OK
Any idea?

**Comment by cakoose** [comment]
Assuming this is fixed.  Please re-open if it isn't fixed.
